; Copyright 2026 PalindromicBreadLoaf (palindromicbreadloaf@tuta.com)
; SPDX-License-Identifier: GPL-3.0-or-later

; Xenoblade Chronicles 2 non-JP

[title]
name = Xenoblade Chronicles 2
title_id = 0100E95004038000
supported = false

[builds]

[presentation]
