; Copyright 2026 PalindromicBreadLoaf (palindromicbreadloaf@tuta.com)
; SPDX-License-Identifier: GPL-3.0-or-later

; Paper Mario: The Thousand-Year Door

[title]
name = Paper Mario: The Thousand-Year Door
title_id = 0100ECD018EBE000
supported = false

[builds]
; build_id = <16 hex digits>, recorded per update version.
1.0.1 = 0EFFE4AF1DEC3A79

[presentation]
; To be populated from instrumentation
; present_interval =
; swapchain_buffers =
; texture_format =
; handheld_width =
; handheld_height =
